

name: Docset Build and Publish
on: 
  push:
    tags:
      - "*"


jobs:
  build-and-publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Prepare
        uses: actions/setup-node@v4
        with:
            node-version: '18'
      - run: sudo npm_config_user=root npm install -g @cc12703m/mddocsetbuilder@1.5.1


      - name: Checkout
        uses: actions/checkout@v4
        with:
            path: './source'


      - name: Build Docset
        run: mddocsetbuilder ./source -o ./out -n learning_note_SoftDev -p tgz 
        working-directory: ${{ github.workspace }}


      - name: Create Release and Upload Asset
        id: release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          body: Release Document
          files: ./out/learning_note_SoftDev.docset.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: submit info
        id: meta
        uses: docker/metadata-action@v5
        with: 
          images: cc12703/learning_note_SoftDev
          tags: type=ref,event=tag
      - id: submit
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'http://notify.cc12703.com:3000/update/submit'
          method: 'POST'
          customHeaders: '{"Accept": "application/json", "Content-Type": "application/json"}'
          data: '{"repoName" : "learning_note_SoftDev", "lastVer" : "${{steps.meta.outputs.version}}", "lastUrl" : "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/learning_note_SoftDev.docset.tgz"}'
          timeout: 30000
      - id: submit_resp
        run: echo ${{ steps.submit.outputs.response }}


        
      
        
